Update Description of Landing Pages with Abstracts
oracle-livelabs/oci pull request #246
Opened 2023-08-14 20:07 UTC by tayzheng

# Add here your WMS ID
11240 - Getting Started with Oracle Cloud Infrastructure,
11241 - Introduction to Cloud Operations on OCI: Managing and Monitoring Resources
11242 - Introduction to OCI Networking and Security,
11231 - Introduction to OCI Financial Operations: Tracking Resources and Consumption,
11244 - Deploying Reference Architectures on OCI,
11245 - Best Practices to Design and Operate OCI,
11246 - Navigating the Impact of Cloud on Your Organization,
11247 - Understanding Multicloud and Hybrid Cloud

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-08-14 20:19 UTC, rahul-tasker requested changes
Hello, it looks like the manifest.json files only contain the introduction and OCW support files. Is this correct? Please include any markdown files that need to be shown to the end user in this file.

Also please resolve the conflicts this branch has with the main branch. 

Thank you!
Rahul

2023-08-14 21:09 UTC, tayzheng commented
Hi, I believe so. All the information we are including for the landing page of our OCW tutorials are in the introduction.md - we are still updating some links which I am waiting to receive to include. But wanted to see the abstract changes reflected for the team to review.

Let me know if there are any other questions or what i need to do on my side. Thanks for your help!

Taylor


Taylor Zheng

Oracle North America Cloud Engineering

Phone: (737) 867-3774 | Mobile: (512) 820 -2775

________________________________
From: Rahul Tasker ***@***.***>
Sent: Monday, August 14, 2023 3:20 PM
To: oracle-livelabs/oci ***@***.***>
Cc: Taylor Zheng ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] Update Description of Landing Pages with Abstracts (PR #246)


@rahul-tasker requested changes on this pull request.

Hello, it looks like the manifest.json files only contain the introduction and OCW support files. Is this correct? Please include any markdown files that need to be shown to the end user in this file.

Also please resolve the conflicts this branch has with the main branch.

Thank you!
Rahul

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/oracle-livelabs/oci/pull/246*pullrequestreview-1577588372__;Iw!!ACWV5N9M2RV99hQ!NnFLsqD8yQeHOtJNOeNMXRTdtqBei5jruzpKJwEGFrMEWS_BhI-BB8it_1hnReyLh7WDxUvH1KbMCcufrvqqn2--Oiw$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ACKU2KMFBQSK55OK2BVHP3LXVKB7HANCNFSM6AAAAAA3QFHHTA__;!!ACWV5N9M2RV99hQ!NnFLsqD8yQeHOtJNOeNMXRTdtqBei5jruzpKJwEGFrMEWS_BhI-BB8it_1hnReyLh7WDxUvH1KbMCcufrvqqGve4oYY$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-15 00:23 UTC, anooshapilli commented
@tayzheng - Please resolve the conflicting files issue to approve the PR.

2023-08-15 17:10 UTC, anooshapilli approved these changes

2023-08-15 17:10 UTC, merged