Workshop creation WMS ID 11462
oracle-livelabs/oci pull request #277
Opened 2023-10-06 18:18 UTC by eliana-romero

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-10-06 19:05 UTC, denisemyrick commented
Hi Eliana please update branch before our review.

2023-10-06 19:55 UTC, eliana-romero commented
Thank you Denise, I've just updated it, let me know if there is something else to do. Thank you so much

2023-10-06 20:10 UTC, denisemyrick requested changes

2023-10-10 13:34 UTC, dannymgithub reviewed
please review you png files, they are also case sensitive

2023-10-10 13:34 UTC, dannymgithub commented on oci-analytics-fast-track-espanol/ft-create-dataset-es-lab-dos/ft-create-dataset-es-lab-dos.md
@eliana-romero your png files should also be lowercased , example: ./images/lab2_t1_1.png

2023-10-10 17:32 UTC, anooshapilli reviewed
@eliana-romero - Please make these images lowercase and rename them to be descriptive
<img width="290" alt="image" src="https://github.com/oracle-livelabs/oci/assets/63126232/e862fe81-dbda-4b43-b9e0-dd87bbd9b90c">
<img width="281" alt="image" src="https://github.com/oracle-livelabs/oci/assets/63126232/e4d58f93-e538-4ef0-8429-ae8f2290fe20">

Please use - or _ instead of spaces and move the file to files folder
<img width="289" alt="image" src="https://github.com/oracle-livelabs/oci/assets/63126232/07c20a7a-13cf-4869-8665-2f386baba840">
<img width="275" alt="image" src="https://github.com/oracle-livelabs/oci/assets/63126232/9e4023b2-473f-49dd-8b51-4a172b447782">

2023-10-11 20:33 UTC, anooshapilli commented
@eliana-romero - Just following up on the requested changes to the PR

2023-10-13 17:59 UTC, anooshapilli commented
@eliana-romero - This PR is open for more than 5 days. Please make the requested changes and create a new PR. Closing the PR for now.

2023-10-16 16:32 UTC, closed without merging