WMS ID: 11264 - Adding "Lakehouse for Manufacturing on OCI "
oracle-livelabs/oci pull request #31
Opened 2022-09-13 17:10 UTC by pavan-upadhyay

WMS ID: 11264 - Creating new workshop "Lakehouse for Manufacturing on OCI "

2022-09-13 18:50 UTC, arabellayao requested changes
Hi! Please fix the following issues of your PR:
1. Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.
2. You should not include any rar or zip files in GitHub. Instead, send the files to livelabs-help-db_us@oracle.com, and we will upload the file and give you a PAR link
3. All images should have alternative texts in the Markdown files for accessibility
4. Images’ names should be descriptive instead of step numbers
5. There may be a typo in lakehouse-for-manufacturing-livelab/qualitydefects/files/ManufacturingLakehouse.jsonl - do you mean "json" instead of "jsonl"?
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

2022-09-14 17:36 UTC, arabellayao requested changes
Hi! Please change lakehouse-for-manufacturing-livelab/qualitydefects/files/ManufacturingLakehouse.json to be all lowercase. Thanks!

2022-09-14 19:11 UTC, pavan-upadhyay commented
Thanks for the review. The mentioned file name changed to lower case and committed.

2022-09-15 02:30 UTC, arabellayao approved these changes

2022-09-15 02:30 UTC, merged