Workshop Creation - WMS ID: 11252
oracle-livelabs/oci pull request #311
Opened 2023-12-28 18:34 UTC by heloisaescobar

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ X] All filenames are lower case (including folders, images, files, etc.)
- [ X] Filenames are descriptive
- [X ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ X] Image references in markdown contain an alternate text

2024-01-02 15:13 UTC, denisemyrick requested changes
Please verify all file names are in lowercase. Please remove LiveLabs-v3.zip

2024-01-02 20:29 UTC, rahul-tasker commented
Please also update this branch, as it is out of date with the base branch.

2024-01-02 21:34 UTC, heloisaescobar commented
updated name to live-labs-v3.zip

2024-01-02 21:35 UTC, heloisaescobar commented
live-labs-v3.zip

2024-01-03 15:02 UTC, denisemyrick requested changes

2024-01-03 15:02 UTC, denisemyrick commented on oci-lakehouse-fast-track/live-labs-v3.zip
Hi, this .zip is still here. Is the .zip necessary for the lab? Is so it needs to be a PAR

2024-01-04 14:03 UTC, denisemyrick commented
Thanks for removing the .zip. I see that the branch is still out of date though. Please update with base and we can approve the request.

2024-01-04 14:25 UTC, heloisaescobar commented
Branch updated.

2024-01-04 14:35 UTC, denisemyrick commented
Sorry, one more file with capitalized letters.
![Screenshot 2024-01-04 at 9 34 27 AM](https://github.com/oracle-livelabs/oci/assets/96066057/6df7d1c4-d59d-4551-964f-a978c6108679)

2024-01-04 16:47 UTC, heloisaescobar commented
Rename 43-SQL-open.png to 43-sql-open.png

2024-01-04 20:00 UTC, ramumg approved these changes

2024-01-04 20:01 UTC, merged