Added Equinix Fabric Cloud Router Deployment Scenario to MultiCloud Network Connectivity Lab 4: FastConnect Deployment
oracle-livelabs/oci pull request #361
Opened 2024-05-22 14:22 UTC by smooreoci

WMS - 11434

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

2024-05-22 15:18 UTC, ramonamagadan18 reviewed
Hi @smooreoci! Please ping me on Slack.

2024-05-23 06:16 UTC, ramonamagadan18 requested changes
Hi @smooreoci! Please make sure that all IP addresses are covered and also update the acknowledgment section in each MS file you modified with the actual date and your name

2024-05-23 17:12 UTC, smooreoci commented
Hello @ramonamagadan18 , I've made the requested changes. Some of the IP routes presented are important to show for to help the user's understanding of the LiveLab.

2024-05-24 06:09 UTC, ramonamagadan18 approved these changes

2024-05-24 06:09 UTC, merged