WMS ID #11726
oracle-livelabs/oci pull request #426
Opened 2024-10-11 21:08 UTC by CDOracle

# Add here your WMS ID: 11726

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

2024-10-11 21:10 UTC, CDOracle commented
We are updating WMS ID: 11726 for an event on Tuesday 10/13/2024

2024-10-14 09:00 UTC, carmenberdant1 requested changes
Hi @CDOracle, please check the step numbers in the apps-cloud-adventure-cio/04-extend-scm-llm/extend-more-po.md folder. Thank you!

2024-10-14 17:18 UTC, CDOracle commented
Cameren,

I corrected the changes to the 1st lab and the lab in the email.

You requested I change the link in the QA part of the lab.  The documentation for edit labs says I must contact livelabs admin to make changes to a lab that is published.  Below is the correct link

https://github.com/oracle-livelabs/oci/tree/main/apps-cloud-adventure-cio

please tell me how to proceed.

Thank you

Casey



***@***.***

***@***.***

From: Carmen Berdant ***@***.***>
Sent: Monday, October 14, 2024 4:01 AM
To: oracle-livelabs/oci ***@***.***>
Cc: Casey Doody ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oci] WMS ID #11726 (PR #426)


@carmenberdant1 requested changes on this pull request.

Hi @CDOracle<https://urldefense.com/v3/__https:/github.com/CDOracle__;!!ACWV5N9M2RV99hQ!NPOFMQ8ISpCOWwPovneNC1drZbkc3KQ3tmT9UgNied_tDTq4rG5QOk8jFXUR4sKlVy7Q2yRHizT4-4oKlSPBf8-3EM8$>, please check the step numbers in the apps-cloud-adventure-cio/04-extend-scm-llm/extend-more-po.md folder. Thank you!

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oci/pull/426*pullrequestreview-2365850549__;Iw!!ACWV5N9M2RV99hQ!NPOFMQ8ISpCOWwPovneNC1drZbkc3KQ3tmT9UgNied_tDTq4rG5QOk8jFXUR4sKlVy7Q2yRHizT4-4oKlSPBnh5vpHg$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/BHBQXWML4RCQ2HY7HBBA273Z3OB3DAVCNFSM6AAAAABPZUUJLCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRVHA2TANJUHE__;!!ACWV5N9M2RV99hQ!NPOFMQ8ISpCOWwPovneNC1drZbkc3KQ3tmT9UgNied_tDTq4rG5QOk8jFXUR4sKlVy7Q2yRHizT4-4oKlSPB3o42mbc$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-10-14 18:00 UTC, carmenberdant1 approved these changes

2024-10-14 18:00 UTC, merged